# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainview_ui_v0.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(526, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.label.setObjectName("label")
        self.SearchList = QtWidgets.QTextBrowser(self.centralwidget)
        self.SearchList.setGeometry(QtCore.QRect(10, 270, 501, 281))
        self.SearchList.setObjectName("SearchList")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 550, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 121, 31))
        self.label_2.setObjectName("label_2")
        self.conditionList = QtWidgets.QListWidget(self.centralwidget)
        self.conditionList.setGeometry(QtCore.QRect(10, 40, 251, 231))
        self.conditionList.setObjectName("conditionList")
        self.conditionList2 = QtWidgets.QListWidget(self.centralwidget)
        self.conditionList2.setGeometry(QtCore.QRect(260, 40, 251, 231))
        self.conditionList2.setObjectName("conditionList2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "조건검색"))
        self.pushButton.setText(_translate("MainWindow", "검색시작"))
        self.label_2.setText(_translate("MainWindow", "기술분석"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
